export const aboutStaticlanguages = {
    en:{
        title:'About us',
        description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pulvinar urna viverra adipiscing venenatis, eget et. Felis ut nisi praesent morbi sagittis, aliquam porttitor fames. Tortor eget non nulla aliquam, adipiscing vulputate sit senectus volutpat. Aliquet vestibulum, diam quam suspendisse pellentesque id. Mauris egestas odio diam nibh. Vestibulum facilisis nunc, semper ipsum ac. Et duis lobortis dui id dolor. Tortor cursus fermentum in risus arcu vitae.',
        box_title:'We are aware of our Social Environmental Responsibility',
        box_description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pulvinar urna viverra adipiscing venenatis, eget et. Felis ut nisi praesent morbi sagittis, aliquam porttitor fames. Tortor eget non nulla aliquam, adipiscing vulputate sit senectus volutpat.',
        approach:'Our Approach',
        approach_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pulvinar urna viverra adipiscing venenatis, eget et. Felis ut nisi praesent morbi sagittis, aliquam porttitor fames. Tortor eget non nulla aliquam, adipiscing vulputate sit senectus',
        bottom_box_1_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pulvinar urna viverra adipiscing venenatis, eget et. Felis ut nisi praesent morbi sagittis, aliquam porttitor fames. Tortor eget non nulla aliquam, adipiscing vulputate sit senectus',
        bottom_box_2_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pulvinar urna viverra adipiscing venenatis, eget et. Felis ut nisi praesent morbi sagittis, aliquam porttitor fames. Tortor eget non nulla aliquam, adipiscing vulputate sit senectus',
        icon1:'Security by Design',
        icon2:'Scalable Solutions',
        icon3:'Tailor made for you',
        icon4:'Empathy - Grow with us',
    },
    fr:{
        title:'À propos de nous',
        description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pulvinar urna viverra adipiscing venenatis, eget et. Felis ut nisi praesent morbi sagittis, aliquam porttitor fames. Tortor eget non nulla aliquam, adipiscing vulputate sit senectus volutpat. Aliquet vestibulum, diam quam suspendisse pellentesque id. Mauris egestas odio diam nibh. Vestibulum facilisis nunc, semper ipsum ac. Et duis lobortis dui id dolor. Tortor cursus fermentum in risus arcu vitae.',
        box_title:'Nous sommes conscients de notre Responsabilité Sociale Environnementale',
        box_description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pulvinar urna viverra adipiscing venenatis, eget et. Felis ut nisi praesent morbi sagittis, aliquam porttitor fames. Tortor eget non nulla aliquam, adipiscing vulputate sit senectus volutpat.',
        approach:'Notre approche',
        approach_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pulvinar urna viverra adipiscing venenatis, eget et. Felis ut nisi praesent morbi sagittis, aliquam porttitor fames. Tortor eget non nulla aliquam, adipiscing vulputate sit senectus',
        bottom_box_1_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pulvinar urna viverra adipiscing venenatis, eget et. Felis ut nisi praesent morbi sagittis, aliquam porttitor fames. Tortor eget non nulla aliquam, adipiscing vulputate sit senectus',
        bottom_box_2_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pulvinar urna viverra adipiscing venenatis, eget et. Felis ut nisi praesent morbi sagittis, aliquam porttitor fames. Tortor eget non nulla aliquam, adipiscing vulputate sit senectus',
        icon1:'Sécurité dès la conception',
        icon2:'Solutions évolutives',
        icon3:'Sur mesure pour vous',
        icon4:'Empathie - Grandissez avec nous',
    }
};