export const footerlanguages = {
    en:{
        whoweare:"WHO WE ARE",
        work:'Work',
        services:'Services',
        careers:'Careers',
        workingprocess:'Working Process',
        whychooseus:'Why Choose Us',
        legal:'Legal',
        privacypolicy:'Privacy Policy',
        cookiespolicy:'Cookies Policy',
        termsandconditions:'Terms and Conditions',
        copyright:'Copyright (c) 2021 Converge2digital. All Rights Reserved',
        home:'Home',
        wish:'Wish',
    },
    fr:{
        whoweare:"QUI NOUS SOMMES",
        work:'Travail',
        services:'Prestations de service',
        careers:'Carrières',
        workingprocess:'Processus de travail',
        whychooseus:'Pourquoi nous choisir',
        legal:'Légale',
        privacypolicy:'Politique de confidentialité',
        cookiespolicy:'Politique de cookies',
        termsandconditions:'Termes et conditions',
        copyright:'Copyright (c) 2021 Converge2digital. Tous les droits sont réservés',
        home:'Accueil',
        wish:'Souhaiter',
    }
};