export const homeStaticlanguages={
    en:{
        homebannerTitle:'Wishes Come True With Us',
        homebannerDescription:'We are a dynamic brand evolving to provide services to make the digital world a better place to encounter with.',
        homebannerLinkText:'Make a wish',
        homesolutionlistTitle:'What we do',
        homesolutionlistDescription:'Become a digital professional by joining with us',
        homeserviceTitle: 'Services',
        homeserviceDescription: 'We have a wide range of services that would cater to you and help you uplift your business and move forward toward a digital driven community.',
        homeserviceLinkText: 'How may we serve you',
        homehowdowedoBannerTitle: 'Secure by Design',
        homehowdowedoBannerDescription: 'We are a dynamic brand evolving to provide services to make the digital world a better place to encounter with.',
        homehowdowedoBannerLinkText: 'Know more',
        home_howdowedo_main_Title: 'How Do We Do',
        home_howdowedo_subsection1_Title: 'Secure by Design',
        home_howdowedo_subsection1_Description: 'We have the security approach in our DNA.',
        home_howdowedo_subsection2_Title: 'Scalable Solutions',
        home_howdowedo_subsection2_Description:'We provide the infrastructure that is Scalable for your future requirements.',
        home_howdowedo_subsection3_Title: 'Tailor made',
        home_howdowedo_subsection3_Description:'Our soutions are tailor made for the requirements which you have.',
        home_howdowedo_subsection4_Title: 'Empathy',
        home_howdowedo_subsection4_Description:'We will grow with you.',
        hometestimonial_title:"We've worked with big and small alike.",

    },
    fr:{
        homebannerTitle:'Les souhaits deviennent réalité',
        homebannerDescription:'Nous sommes une marque dynamique qui évolue pour fournir des services afin de faire du monde numérique un meilleur endroit pour rencontrer.',
        homebannerLinkText:'Faire un vœu',
        homesolutionlistTitle:'Ce que nous faisons',
        homesolutionlistDescription:'Devenez un professionnel du numérique en nous rejoignant',
        homeserviceTitle: 'Prestations de service',
        homeserviceDescription: 'Nous avons une large gamme de services qui vous répondraient et vous aideraient à développer votre entreprise et à progresser vers une communauté axée sur le numérique.',
        homeserviceLinkText: 'Comment pouvons-nous vous servir',
        homehowdowedoBannerTitle: 'Sécurisé par conception',
        homehowdowedoBannerDescription: 'Nous sommes une marque dynamique qui évolue pour fournir des services afin de faire du monde numérique un meilleur endroit pour rencontrer.',
        homehowdowedoBannerLinkText: 'Savoir plus',
        home_howdowedo_main_Title: 'Comment faisons-nous',
        home_howdowedo_subsection1_Title: 'Sécurisé par conception',
        home_howdowedo_subsection1_Description: "Nous avons l'approche sécurité dans notre ADN.",
        home_howdowedo_subsection2_Title: 'Solutions évolutives',
        home_howdowedo_subsection2_Description:"Nous fournissons l'infrastructure évolutive pour vos besoins futurs.",
        home_howdowedo_subsection3_Title: 'Sur mesure',
        home_howdowedo_subsection3_Description:'Nos solutions sont faites sur mesure pour les exigences que vous avez.',
        home_howdowedo_subsection4_Title: 'Empathie',
        home_howdowedo_subsection4_Description:'Nous grandirons avec vous.',
        hometestimonial_title: 'Nous avons travaillé avec des petits comme des grands.'
    }
};