export const languages={
  en:{
    name:'English',
    dashboard:'Dashboard',
    solution:'Solutions',
    solutions:'Solutions',
    solutiontitle:'Solution Title',
    service:'Services',
    servicegroup:'Services Group',
    service_group:'Services Group',
    service_group_title:'Services Group Title',
    soundtrack:'Sound Track',
    soundengineering:'Sound Engineering',
    testimonial:'Testimonial',
    career:'Career',
    profile:'Profile',
    id:'ID',
    hometitle:'HOME TITLE',
    status:'STATUS',
    createdatby:'CREATED AT / BY',
    updatedatby:'UPDATED AT/ BY',
    action:'ACTION',
    servicelist:'SERVICES LIST',
    areyousure:'Are You Sure?',
    ok:'OK',
    yes:'Yes',
    no:'No',
    flagimg:'/images/us-Flag.png',
    myprofile:'My profile',
    settings:'Settings',
    logout:'Logout',
    welcome:'Welcome!',
    music:'music',
    category:'Category',
    musictitle:'Music title',
    artistname:'Artist name',
    musicfile:'Music file',
    photoalbum:'Photo',
    add:'Add',
    testimonialname:'TESTIMONIAL NAME',
    testimonialslist:'TESTIMONIALS LIST',
    title:'Title:',
    contenttitle:'Content Title:',
    servicename:'Service Name:',
    description:'Description:',
    contentdescription:'Contend Description:',
    subtitle:'Sub Title:',
    grouplablename:'Group Lable Name:',
    selecttheserviceshere:'Select the services here',
    selectedservices:'Selected services',
    personname:'Person name',
    designation:'Designation',
    company:'Company',
    message:'Message',
    saveasdraft:'Save as draft',
    saveandpublish:'Save & Publish',
    showonthehomescreen:"show on the home screen",
    home:'HOME',
    page:'PAGE',
    status:'Status',
    statuss:'Status:' ,
    albumphoto:'Photo',
    addnewcategory:'Add new category',
    close:'Close',
    save:'Save',
    savechanges:'Save changes',
    clientimage:'Client Image',
    clientname:'Client Name',
    client:'Client',
    clientnamee:'Client Name:',
    clientlogoo:'Client Logo:',
    showsalarybox:'Show Salary Box',
    location:'Location',
    position:'Position,',
    all:'All',
    draft:'Draft',
    published:'Published',
    service_icon:"Service Icon",
    select:'Select',
    addnewlocation:'Add New Location',
    addnewposition:'Add New Position',
    addnewdesignation:'Add New Designation',
    voice:'Voice',
    voice_title:'Voice Title',
    servicestitle:'services title',
    back:'back'
  },
  fr:{
    name:'French',
    dashboard:'Dasbod',
    solution:'Solutions',
    solutions:'Solutions',
    solutiontitle:'Solution TITRE',
    service:'Col de lutérus',
    servicegroup:'Groupe de services',
    service_group:'Groupe de services',
    service_group_title:'Titre du groupe de services',
    soundtrack:'Bande sonore',
    soundengineering:'Ingénierie du son',
    testimonial:'Témoignage',
    career:'Carrière',
    profile:'Profil',
    id:'IDENTIFIANT',
    hometitle:'TITRE DE LA MAISON',
    status:'STATUT',
    createdatby:'CRÉÉ À / PAR',
    updatedatby:'MIS À JOUR À / PAR',
    action:'ACTION',
    servicelist:'LISTE DES SERVICES',
    areyousure:'Es-tu sûr?',
    ok:"D'accord",
    yes:'S',
    no:'Non',
    flagimg:'/images/fr-Flag.png',
    myprofile:'Mon profil',
    settings:'Paramètres',
    logout:'Se déconnecter',
    welcome:'Bienvenue!',
    music:'musique',
    category:'Catégorie',
    musictitle:'Titre de la musique',
    artistname:"Nom d'artiste",
    musicfile:'Fichier musical',
    photoalbum:'Photo',
    add:'Ajouter',
    testimonialname:'TÉMOIGNAGE NOM',
    testimonialslist:'LISTE DES TÉMOIGNAGES',
    title:'Titre:',
    contenttitle:'Titre du contenu:',
    servicename:'Nom du service:',
    description:'La description:',
    contentdescription:'Description du litige:',
    subtitle:'Sous-titre:',
    grouplablename:"Nom de l'étiquette du groupe:",
    selecttheserviceshere:'Sélectionnez les services ici',
    selectedservices:'Selected services',
    personname:"Nom d'une personne",
    designation:'La désignation',
    company:'Société',
    message:'Un message',
    saveasdraft:'Enregistrer comme brouillon',
    saveandpublish:'Enregistrer et publier',
    showonthehomescreen:"afficher sur l'écran d'accueil",
    home:'DOMICILE',
    page:'PAGE',
    statuss:'Statut:',
    albumphoto:'Photo',
    addnewcategory:'Ajouter une nouvelle catégorie',
    close:'Proche',
    save:'Sauvegarder',
    savechanges:'Sauvegarder les modifications',
    clientimage:'Image du client',
    clientname:'Nom du client',
    client:'Cliente',
    clientnamee:'Nom du client:',
    clientlogoo:'Logo du client:',
    showsalarybox:'Afficher la boîte de salaire',
    location:'Emplacement',
    position:'Position',
    all:'Toute',
    draft:'Thrabite',
    published:'Publier',
    service_icon:"Icône_service",
    select:'sélectionner',
    addnewlocation:'Ajouter un nouvel emplacement',
    addnewposition:'Ajouter un nouveau poste',
    addnewdesignation:'Ajouter une nouvelle désignation',
    voice:'Voix',
    voice_title:'Titre de la voix',
    servicestitle:'titre des services',
    back:'Arrière'
  }
};